# Generated by Django 5.2.5 on 2025-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_funding_goal_startup_location_startup_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
