# Generated by Django 5.2.5 on 2025-08-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_equity_startup_valuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='valuation',
        ),
    ]
