# Generated by Django 5.2.5 on 2025-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_remove_startup_equity_remove_startup_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
