# Generated by Django 5.2.5 on 2025-08-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_founderprofile_company_founderprofile_email_and_more'),
        ('startups', '0008_alter_startup_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='profiles.founderprofile'),
        ),
    ]
