# Generated by Django 5.2.5 on 2025-08-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_alter_startup_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
