# Generated by Django 5.2.5 on 2025-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0011_startup_raised_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='raised_amount',
        ),
        migrations.AddField(
            model_name='startup',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
